apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docs-devintripp-com
spec:
  secretName: docs-devintripp-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - docs.devintripp.com
